DEF NUM_PLAYER_NAMES EQU 3

IF DEF(_RED)
DEF PLAYERNAME1 EQUS "РЕД"
DEF PLAYERNAME2 EQUS "ЕШ"
DEF PLAYERNAME3 EQUS "ДЖЕК"

DEF RIVALNAME1 EQUS "БЛУ"
DEF RIVALNAME2 EQUS "ГЕРІ"
DEF RIVALNAME3 EQUS "ДЖОН"
ENDC

IF DEF(_BLUE)
DEF PLAYERNAME1 EQUS "БЛУ"
DEF PLAYERNAME2 EQUS "ГЕРІ"
DEF PLAYERNAME3 EQUS "ДЖОН"

DEF RIVALNAME1 EQUS "РЕД"
DEF RIVALNAME2 EQUS "ЕШ"
DEF RIVALNAME3 EQUS "ДЖЕК"
ENDC
